esphome:
  name: esp-light-bar
  friendly_name: esp-light-bar

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR-API-KEY"

ota:
  password: "YOUR-OTA-PASSWORD"

wifi: (YOUR_WIFI_DETAILS)
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-LIGHT-BAR"
    password: "YOUR_AP_PASSWORD"

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO3
    num_leds: 43
    name: "Hub"
    id: esphub
    internal: true


  - platform: partition
    name: "Light Bar 1"
    segments:
      # Use first 10 LEDs from the light with ID light1
      - id: esphub
        from: 0
        to: 13

  - platform: partition
    name: "Light Bar 2"
    segments:
      # Use LEDs 11-20 from the light with ID light1
      - id: esphub
        from: 14
        to: 27

  - platform: partition
    name: "Light Bar 3"
    segments:
      # Use LEDs 11-20 from the light with ID light1
      - id: esphub
        from: 28
        to: 42
